### ISSUE TITLE
Can't run 'npm install' or 'npm ci'

### ISSUE THREAD

**Issue by LeBodro** [qwertyuu/quebec-achat-local#8]
Error I get when running `npm install` or `npm ci`:
```
fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

TypeError: path must be a string or Buffer
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.writeFileSync (fs.js:1291:33)
    at Object.<anonymous> (C:\git\quebec-achat-local\gcpSetup.js:2:4)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
```

**Comment by qwertyuu** [comment]
Devrait être réglé!
